<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260219102503 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE libros (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(255) NOT NULL, autor VARCHAR(200) NOT NULL, isbn VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B7E5AFE6CC1CF4E6 ON libros (isbn)');
        $this->addSql('CREATE TABLE prestamos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha_prestamo TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_devolucion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, usuario_id INT NOT NULL, libro_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4849844FDB38439E ON prestamos (usuario_id)');
        $this->addSql('CREATE INDEX IDX_4849844FC0238522 ON prestamos (libro_id)');
        $this->addSql('CREATE INDEX idx_fecha_prestamo ON prestamos (fecha_prestamo)');
        $this->addSql('CREATE INDEX idx_fecha_devolucion ON prestamos (fecha_devolucion)');
        $this->addSql('CREATE TABLE usuarios (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(100) NOT NULL, apellidos VARCHAR(150) NOT NULL, dni VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EF687F27F8F253B ON usuarios (dni)');
        $this->addSql('ALTER TABLE prestamos ADD CONSTRAINT FK_4849844FDB38439E FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prestamos ADD CONSTRAINT FK_4849844FC0238522 FOREIGN KEY (libro_id) REFERENCES libros (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE prestamos DROP CONSTRAINT FK_4849844FDB38439E');
        $this->addSql('ALTER TABLE prestamos DROP CONSTRAINT FK_4849844FC0238522');
        $this->addSql('DROP TABLE libros');
        $this->addSql('DROP TABLE prestamos');
        $this->addSql('DROP TABLE usuarios');
    }
}
